{
    "cod":"200",
    "message":0,
    "cnt":40,
    "list":[
       {
          "dt":1692684000,
          "main":{
             "temp":296.63,
             "feels_like":297.07,
             "temp_min":296.63,
             "temp_max":298.56,
             "pressure":1020,
             "sea_level":1020,
             "grnd_level":997,
             "humidity":78,
             "temp_kf":-1.93
          },
          "weather":[
             {
                "id":800,
                "main":"Clear",
                "description":"clear sky",
                "icon":"01d"
             }
          ],
          "clouds":{
             "all":0
          },
          "wind":{
             "speed":0.78,
             "deg":331,
             "gust":1.26
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2023-08-22 06:00:00"
       },
       {
          "dt":1692694800,
          "main":{
             "temp":299.25,
             "feels_like":299.25,
             "temp_min":299.25,
             "temp_max":304.48,
             "pressure":1020,
             "sea_level":1020,
             "grnd_level":998,
             "humidity":65,
             "temp_kf":-5.23
          },
          "weather":[
             {
                "id":800,
                "main":"Clear",
                "description":"clear sky",
                "icon":"01d"
             }
          ],
          "clouds":{
             "all":1
          },
          "wind":{
             "speed":0.69,
             "deg":292,
             "gust":1.56
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2023-08-22 09:00:00"
       },
       {
          "dt":1692705600,
          "main":{
             "temp":304.68,
             "feels_like":305.65,
             "temp_min":304.68,
             "temp_max":308.7,
             "pressure":1018,
             "sea_level":1018,
             "grnd_level":996,
             "humidity":45,
             "temp_kf":-4.02
          },
          "weather":[
             {
                "id":800,
                "main":"Clear",
                "description":"clear sky",
                "icon":"01d"
             }
          ],
          "clouds":{
             "all":2
          },
          "wind":{
             "speed":0.48,
             "deg":277,
             "gust":2.43
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2023-08-22 12:00:00"
       },
       {
          "dt":1692716400,
          "main":{
             "temp":309.07,
             "feels_like":308.09,
             "temp_min":309.07,
             "temp_max":309.07,
             "pressure":1016,
             "sea_level":1016,
             "grnd_level":995,
             "humidity":25,
             "temp_kf":0
          },
          "weather":[
             {
                "id":800,
                "main":"Clear",
                "description":"clear sky",
                "icon":"01d"
             }
          ],
          "clouds":{
             "all":7
          },
          "wind":{
             "speed":1.47,
             "deg":299,
             "gust":4.08
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2023-08-22 15:00:00"
       },
       {
          "dt":1692727200,
          "main":{
             "temp":303.91,
             "feels_like":303.76,
             "temp_min":303.91,
             "temp_max":303.91,
             "pressure":1015,
             "sea_level":1015,
             "grnd_level":994,
             "humidity":40,
             "temp_kf":0
          },
          "weather":[
             {
                "id":801,
                "main":"Clouds",
                "description":"few clouds",
                "icon":"02n"
             }
          ],
          "clouds":{
             "all":18
          },
          "wind":{
             "speed":2.38,
             "deg":248,
             "gust":5.64
          },
          "visibility":10000,
          "pop":0.07,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2023-08-22 18:00:00"
       },
       {
          "dt":1692738000,
          "main":{
             "temp":299.55,
             "feels_like":299.55,
             "temp_min":299.55,
             "temp_max":299.55,
             "pressure":1017,
             "sea_level":1017,
             "grnd_level":996,
             "humidity":61,
             "temp_kf":0
          },
          "weather":[
             {
                "id":802,
                "main":"Clouds",
                "description":"scattered clouds",
                "icon":"03n"
             }
          ],
          "clouds":{
             "all":36
          },
          "wind":{
             "speed":2.86,
             "deg":339,
             "gust":5.85
          },
          "visibility":10000,
          "pop":0.31,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2023-08-22 21:00:00"
       },
       {
          "dt":1692748800,
          "main":{
             "temp":297.86,
             "feels_like":298.19,
             "temp_min":297.86,
             "temp_max":297.86,
             "pressure":1017,
             "sea_level":1017,
             "grnd_level":995,
             "humidity":69,
             "temp_kf":0
          },
          "weather":[
             {
                "id":801,
                "main":"Clouds",
                "description":"few clouds",
                "icon":"02n"
             }
          ],
          "clouds":{
             "all":21
          },
          "wind":{
             "speed":1.69,
             "deg":290,
             "gust":2.73
          },
          "visibility":10000,
          "pop":0.27,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2023-08-23 00:00:00"
       },
       {
          "dt":1692759600,
          "main":{
             "temp":296.81,
             "feels_like":297.11,
             "temp_min":296.81,
             "temp_max":296.81,
             "pressure":1017,
             "sea_level":1017,
             "grnd_level":995,
             "humidity":72,
             "temp_kf":0
          },
          "weather":[
             {
                "id":801,
                "main":"Clouds",
                "description":"few clouds",
                "icon":"02n"
             }
          ],
          "clouds":{
             "all":17
          },
          "wind":{
             "speed":2.22,
             "deg":316,
             "gust":5.71
          },
          "visibility":10000,
          "pop":0.31,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2023-08-23 03:00:00"
       },
       {
          "dt":1692770400,
          "main":{
             "temp":297.77,
             "feels_like":298.12,
             "temp_min":297.77,
             "temp_max":297.77,
             "pressure":1018,
             "sea_level":1018,
             "grnd_level":996,
             "humidity":70,
             "temp_kf":0
          },
          "weather":[
             {
                "id":500,
                "main":"Rain",
                "description":"light rain",
                "icon":"10d"
             }
          ],
          "clouds":{
             "all":49
          },
          "wind":{
             "speed":3.36,
             "deg":304,
             "gust":6.52
          },
          "visibility":10000,
          "pop":0.25,
          "rain":{
             "3h":0.35
          },
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2023-08-23 06:00:00"
       },
       {
          "dt":1692781200,
          "main":{
             "temp":302.19,
             "feels_like":302.86,
             "temp_min":302.19,
             "temp_max":302.19,
             "pressure":1018,
             "sea_level":1018,
             "grnd_level":997,
             "humidity":50,
             "temp_kf":0
          },
          "weather":[
             {
                "id":803,
                "main":"Clouds",
                "description":"broken clouds",
                "icon":"04d"
             }
          ],
          "clouds":{
             "all":81
          },
          "wind":{
             "speed":3.74,
             "deg":321,
             "gust":4.7
          },
          "visibility":10000,
          "pop":0.08,
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2023-08-23 09:00:00"
       },
       {
          "dt":1692792000,
          "main":{
             "temp":305.24,
             "feels_like":305.38,
             "temp_min":305.24,
             "temp_max":305.24,
             "pressure":1017,
             "sea_level":1017,
             "grnd_level":996,
             "humidity":39,
             "temp_kf":0
          },
          "weather":[
             {
                "id":802,
                "main":"Clouds",
                "description":"scattered clouds",
                "icon":"03d"
             }
          ],
          "clouds":{
             "all":49
          },
          "wind":{
             "speed":3.24,
             "deg":319,
             "gust":5.46
          },
          "visibility":10000,
          "pop":0.06,
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2023-08-23 12:00:00"
       },
       {
          "dt":1692802800,
          "main":{
             "temp":305.55,
             "feels_like":305.47,
             "temp_min":305.55,
             "temp_max":305.55,
             "pressure":1016,
             "sea_level":1016,
             "grnd_level":995,
             "humidity":37,
             "temp_kf":0
          },
          "weather":[
             {
                "id":801,
                "main":"Clouds",
                "description":"few clouds",
                "icon":"02d"
             }
          ],
          "clouds":{
             "all":16
          },
          "wind":{
             "speed":3.6,
             "deg":317,
             "gust":5.33
          },
          "visibility":10000,
          "pop":0.01,
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2023-08-23 15:00:00"
       },
       {
          "dt":1692813600,
          "main":{
             "temp":301.78,
             "feels_like":302.03,
             "temp_min":301.78,
             "temp_max":301.78,
             "pressure":1016,
             "sea_level":1016,
             "grnd_level":995,
             "humidity":47,
             "temp_kf":0
          },
          "weather":[
             {
                "id":802,
                "main":"Clouds",
                "description":"scattered clouds",
                "icon":"03n"
             }
          ],
          "clouds":{
             "all":41
          },
          "wind":{
             "speed":1.83,
             "deg":9,
             "gust":4.39
          },
          "visibility":10000,
          "pop":0.07,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2023-08-23 18:00:00"
       },
       {
          "dt":1692824400,
          "main":{
             "temp":298.86,
             "feels_like":298.92,
             "temp_min":298.86,
             "temp_max":298.86,
             "pressure":1018,
             "sea_level":1018,
             "grnd_level":996,
             "humidity":55,
             "temp_kf":0
          },
          "weather":[
             {
                "id":802,
                "main":"Clouds",
                "description":"scattered clouds",
                "icon":"03n"
             }
          ],
          "clouds":{
             "all":28
          },
          "wind":{
             "speed":0.9,
             "deg":1,
             "gust":1.97
          },
          "visibility":10000,
          "pop":0.05,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2023-08-23 21:00:00"
       },
       {
          "dt":1692835200,
          "main":{
             "temp":297.12,
             "feels_like":297.19,
             "temp_min":297.12,
             "temp_max":297.12,
             "pressure":1018,
             "sea_level":1018,
             "grnd_level":996,
             "humidity":62,
             "temp_kf":0
          },
          "weather":[
             {
                "id":801,
                "main":"Clouds",
                "description":"few clouds",
                "icon":"02n"
             }
          ],
          "clouds":{
             "all":17
          },
          "wind":{
             "speed":1.12,
             "deg":312,
             "gust":1.85
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2023-08-24 00:00:00"
       },
       {
          "dt":1692846000,
          "main":{
             "temp":295.71,
             "feels_like":295.88,
             "temp_min":295.71,
             "temp_max":295.71,
             "pressure":1018,
             "sea_level":1018,
             "grnd_level":996,
             "humidity":71,
             "temp_kf":0
          },
          "weather":[
             {
                "id":800,
                "main":"Clear",
                "description":"clear sky",
                "icon":"01n"
             }
          ],
          "clouds":{
             "all":1
          },
          "wind":{
             "speed":1.13,
             "deg":319,
             "gust":1.95
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2023-08-24 03:00:00"
       },
       {
          "dt":1692856800,
          "main":{
             "temp":297.07,
             "feels_like":297.27,
             "temp_min":297.07,
             "temp_max":297.07,
             "pressure":1018,
             "sea_level":1018,
             "grnd_level":997,
             "humidity":67,
             "temp_kf":0
          },
          "weather":[
             {
                "id":800,
                "main":"Clear",
                "description":"clear sky",
                "icon":"01d"
             }
          ],
          "clouds":{
             "all":1
          },
          "wind":{
             "speed":1.08,
             "deg":319,
             "gust":1.71
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2023-08-24 06:00:00"
       },
       {
          "dt":1692867600,
          "main":{
             "temp":302.1,
             "feels_like":302.29,
             "temp_min":302.1,
             "temp_max":302.1,
             "pressure":1018,
             "sea_level":1018,
             "grnd_level":997,
             "humidity":46,
             "temp_kf":0
          },
          "weather":[
             {
                "id":800,
                "main":"Clear",
                "description":"clear sky",
                "icon":"01d"
             }
          ],
          "clouds":{
             "all":0
          },
          "wind":{
             "speed":1.5,
             "deg":330,
             "gust":2.06
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2023-08-24 09:00:00"
       },
       {
          "dt":1692878400,
          "main":{
             "temp":305.62,
             "feels_like":305.07,
             "temp_min":305.62,
             "temp_max":305.62,
             "pressure":1016,
             "sea_level":1016,
             "grnd_level":995,
             "humidity":34,
             "temp_kf":0
          },
          "weather":[
             {
                "id":800,
                "main":"Clear",
                "description":"clear sky",
                "icon":"01d"
             }
          ],
          "clouds":{
             "all":1
          },
          "wind":{
             "speed":1.85,
             "deg":342,
             "gust":3.23
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2023-08-24 12:00:00"
       },
       {
          "dt":1692889200,
          "main":{
             "temp":305.92,
             "feels_like":305.01,
             "temp_min":305.92,
             "temp_max":305.92,
             "pressure":1015,
             "sea_level":1015,
             "grnd_level":994,
             "humidity":31,
             "temp_kf":0
          },
          "weather":[
             {
                "id":800,
                "main":"Clear",
                "description":"clear sky",
                "icon":"01d"
             }
          ],
          "clouds":{
             "all":5
          },
          "wind":{
             "speed":2.65,
             "deg":345,
             "gust":3.11
          },
          "visibility":10000,
          "pop":0.01,
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2023-08-24 15:00:00"
       },
       {
          "dt":1692900000,
          "main":{
             "temp":301.79,
             "feels_like":301.32,
             "temp_min":301.79,
             "temp_max":301.79,
             "pressure":1014,
             "sea_level":1014,
             "grnd_level":993,
             "humidity":39,
             "temp_kf":0
          },
          "weather":[
             {
                "id":800,
                "main":"Clear",
                "description":"clear sky",
                "icon":"01n"
             }
          ],
          "clouds":{
             "all":7
          },
          "wind":{
             "speed":2.19,
             "deg":84,
             "gust":4.13
          },
          "visibility":10000,
          "pop":0.01,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2023-08-24 18:00:00"
       },
       {
          "dt":1692910800,
          "main":{
             "temp":299.27,
             "feels_like":299.27,
             "temp_min":299.27,
             "temp_max":299.27,
             "pressure":1015,
             "sea_level":1015,
             "grnd_level":993,
             "humidity":45,
             "temp_kf":0
          },
          "weather":[
             {
                "id":803,
                "main":"Clouds",
                "description":"broken clouds",
                "icon":"04n"
             }
          ],
          "clouds":{
             "all":80
          },
          "wind":{
             "speed":1.63,
             "deg":122,
             "gust":3.53
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2023-08-24 21:00:00"
       },
       {
          "dt":1692921600,
          "main":{
             "temp":297.36,
             "feels_like":297.17,
             "temp_min":297.36,
             "temp_max":297.36,
             "pressure":1014,
             "sea_level":1014,
             "grnd_level":993,
             "humidity":51,
             "temp_kf":0
          },
          "weather":[
             {
                "id":803,
                "main":"Clouds",
                "description":"broken clouds",
                "icon":"04n"
             }
          ],
          "clouds":{
             "all":66
          },
          "wind":{
             "speed":1.87,
             "deg":125,
             "gust":5.26
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2023-08-25 00:00:00"
       },
       {
          "dt":1692932400,
          "main":{
             "temp":295.65,
             "feels_like":295.42,
             "temp_min":295.65,
             "temp_max":295.65,
             "pressure":1013,
             "sea_level":1013,
             "grnd_level":991,
             "humidity":56,
             "temp_kf":0
          },
          "weather":[
             {
                "id":802,
                "main":"Clouds",
                "description":"scattered clouds",
                "icon":"03n"
             }
          ],
          "clouds":{
             "all":32
          },
          "wind":{
             "speed":1.8,
             "deg":116,
             "gust":4.7
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2023-08-25 03:00:00"
       },
       {
          "dt":1692943200,
          "main":{
             "temp":297.08,
             "feels_like":297.07,
             "temp_min":297.08,
             "temp_max":297.08,
             "pressure":1013,
             "sea_level":1013,
             "grnd_level":991,
             "humidity":59,
             "temp_kf":0
          },
          "weather":[
             {
                "id":802,
                "main":"Clouds",
                "description":"scattered clouds",
                "icon":"03d"
             }
          ],
          "clouds":{
             "all":27
          },
          "wind":{
             "speed":1.44,
             "deg":142,
             "gust":2.71
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2023-08-25 06:00:00"
       },
       {
          "dt":1692954000,
          "main":{
             "temp":303.12,
             "feels_like":303.71,
             "temp_min":303.12,
             "temp_max":303.12,
             "pressure":1012,
             "sea_level":1012,
             "grnd_level":991,
             "humidity":47,
             "temp_kf":0
          },
          "weather":[
             {
                "id":802,
                "main":"Clouds",
                "description":"scattered clouds",
                "icon":"03d"
             }
          ],
          "clouds":{
             "all":34
          },
          "wind":{
             "speed":1.92,
             "deg":131,
             "gust":2.3
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2023-08-25 09:00:00"
       },
       {
          "dt":1692964800,
          "main":{
             "temp":308.43,
             "feels_like":308.93,
             "temp_min":308.43,
             "temp_max":308.43,
             "pressure":1011,
             "sea_level":1011,
             "grnd_level":990,
             "humidity":33,
             "temp_kf":0
          },
          "weather":[
             {
                "id":802,
                "main":"Clouds",
                "description":"scattered clouds",
                "icon":"03d"
             }
          ],
          "clouds":{
             "all":28
          },
          "wind":{
             "speed":1.04,
             "deg":184,
             "gust":1.87
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2023-08-25 12:00:00"
       },
       {
          "dt":1692975600,
          "main":{
             "temp":309.61,
             "feels_like":309.52,
             "temp_min":309.61,
             "temp_max":309.61,
             "pressure":1009,
             "sea_level":1009,
             "grnd_level":988,
             "humidity":28,
             "temp_kf":0
          },
          "weather":[
             {
                "id":800,
                "main":"Clear",
                "description":"clear sky",
                "icon":"01d"
             }
          ],
          "clouds":{
             "all":6
          },
          "wind":{
             "speed":0.25,
             "deg":40,
             "gust":2.14
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2023-08-25 15:00:00"
       },
       {
          "dt":1692986400,
          "main":{
             "temp":304.91,
             "feels_like":305.26,
             "temp_min":304.91,
             "temp_max":304.91,
             "pressure":1009,
             "sea_level":1009,
             "grnd_level":988,
             "humidity":41,
             "temp_kf":0
          },
          "weather":[
             {
                "id":801,
                "main":"Clouds",
                "description":"few clouds",
                "icon":"02n"
             }
          ],
          "clouds":{
             "all":21
          },
          "wind":{
             "speed":1.13,
             "deg":167,
             "gust":2.95
          },
          "visibility":10000,
          "pop":0.02,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2023-08-25 18:00:00"
       },
       {
          "dt":1692997200,
          "main":{
             "temp":301.91,
             "feels_like":302.5,
             "temp_min":301.91,
             "temp_max":301.91,
             "pressure":1010,
             "sea_level":1010,
             "grnd_level":989,
             "humidity":50,
             "temp_kf":0
          },
          "weather":[
             {
                "id":802,
                "main":"Clouds",
                "description":"scattered clouds",
                "icon":"03n"
             }
          ],
          "clouds":{
             "all":46
          },
          "wind":{
             "speed":1.95,
             "deg":289,
             "gust":4.98
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2023-08-25 21:00:00"
       },
       {
          "dt":1693008000,
          "main":{
             "temp":299.97,
             "feels_like":300.46,
             "temp_min":299.97,
             "temp_max":299.97,
             "pressure":1010,
             "sea_level":1010,
             "grnd_level":988,
             "humidity":51,
             "temp_kf":0
          },
          "weather":[
             {
                "id":803,
                "main":"Clouds",
                "description":"broken clouds",
                "icon":"04n"
             }
          ],
          "clouds":{
             "all":72
          },
          "wind":{
             "speed":0.85,
             "deg":319,
             "gust":1.73
          },
          "visibility":10000,
          "pop":0.04,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2023-08-26 00:00:00"
       },
       {
          "dt":1693018800,
          "main":{
             "temp":297.77,
             "feels_like":297.88,
             "temp_min":297.77,
             "temp_max":297.77,
             "pressure":1011,
             "sea_level":1011,
             "grnd_level":989,
             "humidity":61,
             "temp_kf":0
          },
          "weather":[
             {
                "id":500,
                "main":"Rain",
                "description":"light rain",
                "icon":"10n"
             }
          ],
          "clouds":{
             "all":94
          },
          "wind":{
             "speed":2.56,
             "deg":295,
             "gust":6.64
          },
          "visibility":10000,
          "pop":0.41,
          "rain":{
             "3h":0.29
          },
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2023-08-26 03:00:00"
       },
       {
          "dt":1693029600,
          "main":{
             "temp":296.17,
             "feels_like":296.59,
             "temp_min":296.17,
             "temp_max":296.17,
             "pressure":1012,
             "sea_level":1012,
             "grnd_level":990,
             "humidity":79,
             "temp_kf":0
          },
          "weather":[
             {
                "id":500,
                "main":"Rain",
                "description":"light rain",
                "icon":"10d"
             }
          ],
          "clouds":{
             "all":95
          },
          "wind":{
             "speed":4.41,
             "deg":307,
             "gust":9.04
          },
          "visibility":10000,
          "pop":0.93,
          "rain":{
             "3h":1.58
          },
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2023-08-26 06:00:00"
       },
       {
          "dt":1693040400,
          "main":{
             "temp":301.68,
             "feels_like":302.55,
             "temp_min":301.68,
             "temp_max":301.68,
             "pressure":1012,
             "sea_level":1012,
             "grnd_level":990,
             "humidity":53,
             "temp_kf":0
          },
          "weather":[
             {
                "id":801,
                "main":"Clouds",
                "description":"few clouds",
                "icon":"02d"
             }
          ],
          "clouds":{
             "all":23
          },
          "wind":{
             "speed":2.25,
             "deg":333,
             "gust":2.83
          },
          "visibility":10000,
          "pop":0.05,
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2023-08-26 09:00:00"
       },
       {
          "dt":1693051200,
          "main":{
             "temp":306.14,
             "feels_like":306.5,
             "temp_min":306.14,
             "temp_max":306.14,
             "pressure":1011,
             "sea_level":1011,
             "grnd_level":990,
             "humidity":38,
             "temp_kf":0
          },
          "weather":[
             {
                "id":801,
                "main":"Clouds",
                "description":"few clouds",
                "icon":"02d"
             }
          ],
          "clouds":{
             "all":23
          },
          "wind":{
             "speed":1.44,
             "deg":348,
             "gust":1.38
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2023-08-26 12:00:00"
       },
       {
          "dt":1693062000,
          "main":{
             "temp":307.09,
             "feels_like":307.11,
             "temp_min":307.09,
             "temp_max":307.09,
             "pressure":1009,
             "sea_level":1009,
             "grnd_level":988,
             "humidity":34,
             "temp_kf":0
          },
          "weather":[
             {
                "id":801,
                "main":"Clouds",
                "description":"few clouds",
                "icon":"02d"
             }
          ],
          "clouds":{
             "all":18
          },
          "wind":{
             "speed":1.39,
             "deg":79,
             "gust":1.43
          },
          "visibility":10000,
          "pop":0.01,
          "sys":{
             "pod":"d"
          },
          "dt_txt":"2023-08-26 15:00:00"
       },
       {
          "dt":1693072800,
          "main":{
             "temp":303.38,
             "feels_like":303.63,
             "temp_min":303.38,
             "temp_max":303.38,
             "pressure":1008,
             "sea_level":1008,
             "grnd_level":987,
             "humidity":44,
             "temp_kf":0
          },
          "weather":[
             {
                "id":802,
                "main":"Clouds",
                "description":"scattered clouds",
                "icon":"03n"
             }
          ],
          "clouds":{
             "all":25
          },
          "wind":{
             "speed":1.88,
             "deg":89,
             "gust":3.8
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2023-08-26 18:00:00"
       },
       {
          "dt":1693083600,
          "main":{
             "temp":300.83,
             "feels_like":301.5,
             "temp_min":300.83,
             "temp_max":300.83,
             "pressure":1007,
             "sea_level":1007,
             "grnd_level":986,
             "humidity":53,
             "temp_kf":0
          },
          "weather":[
             {
                "id":800,
                "main":"Clear",
                "description":"clear sky",
                "icon":"01n"
             }
          ],
          "clouds":{
             "all":8
          },
          "wind":{
             "speed":2.05,
             "deg":136,
             "gust":5.28
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2023-08-26 21:00:00"
       },
       {
          "dt":1693094400,
          "main":{
             "temp":299.09,
             "feels_like":299.31,
             "temp_min":299.09,
             "temp_max":299.09,
             "pressure":1006,
             "sea_level":1006,
             "grnd_level":985,
             "humidity":60,
             "temp_kf":0
          },
          "weather":[
             {
                "id":801,
                "main":"Clouds",
                "description":"few clouds",
                "icon":"02n"
             }
          ],
          "clouds":{
             "all":12
          },
          "wind":{
             "speed":2.21,
             "deg":128,
             "gust":6.04
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2023-08-27 00:00:00"
       },
       {
          "dt":1693105200,
          "main":{
             "temp":296.53,
             "feels_like":296.8,
             "temp_min":296.53,
             "temp_max":296.53,
             "pressure":1007,
             "sea_level":1007,
             "grnd_level":985,
             "humidity":72,
             "temp_kf":0
          },
          "weather":[
             {
                "id":804,
                "main":"Clouds",
                "description":"overcast clouds",
                "icon":"04n"
             }
          ],
          "clouds":{
             "all":85
          },
          "wind":{
             "speed":4.8,
             "deg":285,
             "gust":9.97
          },
          "visibility":10000,
          "pop":0,
          "sys":{
             "pod":"n"
          },
          "dt_txt":"2023-08-27 03:00:00"
       }
    ],
    "city":{
       "id":2761369,
       "name":"Vienna",
       "coord":{
          "lat":48.2085,
          "lon":16.3721
       },
       "country":"AT",
       "population":1000000,
       "timezone":7200,
       "sunrise":1692676675,
       "sunset":1692727051
    }
 }